### ISSUE TITLE
Set grass_main to external

### ISSUE THREAD

**Issue by SoulyVEVO** [DDNetPP/maps#46]
It will save some file size

Shadow tiles can be replaced by those included in `blmapchill_txt`
![blmapchill_txt](https://user-images.githubusercontent.com/61762251/110419814-54259480-809a-11eb-8ac9-53eb00d74067.png)

**Comment by fokkonaut** [comment]
grass_main is embedded on purpose, for 0.7 clients, because I really dislike the grass_main_0.7. Its all like it should be, I just need to implement fast download for ddnet clients somehow.

**Comment by ChillerDragon** [comment]
@fokkonaut I think @SoulyVEVO has a point here. You can use the 0.7 grass_main to map in 0.6 style there were only grass tiles added and as far as I see it the old ones are unchanged. The shadow got removed but we have that in blmapchill_txt so that can probably safe a few bytes without changing the look of the map.



![teeworlds](https://raw.githubusercontent.com/teeworlds/teeworlds/6c6a3a0bb39caff5af643fc369c5edef2bbd3be9/datasrc/mapres/grass_main.png)

![ddnet](https://raw.githubusercontent.com/ddnet/ddnet/e2cb24b7d9ef43f840716a8b26661a9713be6051/data/mapres/grass_main.png)

**Comment by fokkonaut** [comment]
It doesnt change much, best would be to maintain two versions, but since I am not a fan of that, I would just keep it like it is. Thanks.
