### ISSUE TITLE
UNDERGROUND NOBO PLOT

### ISSUE THREAD

**Issue by ghost** [DDNetPP/maps#87]
![image](https://user-images.githubusercontent.com/99206072/153230233-5980191e-3db7-4d9c-8d9f-fdbb915a4ce1.png)

**Comment by ghost** [comment]
also i would accept if the flying bank would be put in the island next to it :)

**Comment by ChillerDragon** [comment]
> also i would accept if the flying bank would be put in the island next to it :)

wat ?xd

**Comment by ChillerDragon** [comment]
I actually would keep the plots rare as they are. Or even make them more rare. To encourage player plot trades instead of buying it directly from the shop. To create some interesting user driven real estate market.

**Comment by ghost** [comment]
nice

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/99206072/153230705-eca62dd9-a3c1-4d7f-97fd-606940728a3c.png)
this bank in the island would be cool
![image](https://user-images.githubusercontent.com/99206072/153230879-fb1c4cec-2145-40dd-bdae-cf22b5eff823.png)

**Comment by ghost** [comment]
also including the new spawn you made

**Comment by ChillerDragon** [comment]
Sounds like a different issue to me.

**Comment by ChillerDragon** [comment]
The player count is low these days so as I already said a low plot amount incentives user trades which can create an more interesting market than fixed prices from the shop. Also the step stairs feel weird and the block gameplay allows for passive play styles to stall players. So I am rejecting the proposal of adding a new plot.

The bank in the island could work yes. But it requires some work and planning to make it good. If you are still interested in doing that you can propose a new issue just about moving the bank and come up with some concrete proposal. But I do not think it is worth the effort because the current bank is fine. But I do actually dislike the lack of freeze and amount of hookable in the island. It causes horrible block gameplay so integrating the unhookable bank there could solve the gameplay issue.
